### ISSUE TITLE
Shopware sagt: Lizenz fehlt

### ISSUE THREAD

**Issue by JohnGiddi** [FriendsOfShopware/FroshProfiler#103]
Hello!
How to licence?

Greetings

John Giddi

**Comment by teiling88** [comment]
https://store.shopware.com/frosh14879865239f/profiler.html <-- "buy" it there with your shopware account which is connected to your shop domain.

**Comment by shyim** [comment]
As already @teiling88 mentioned, it's should be fixed after free bought from Store.
