### ISSUE TITLE
Make toolbar toggleable

### ISSUE THREAD

**Issue by arboro** [FriendsOfShopware/FroshProfiler#107]
Sometimes, you don't want the toolbar to overlap certain elements, but you don't want to deactivate it either, so it would be nice to have the option to just toggle the toolbar whenever you feel like it.

**Comment by arboro** [comment]
This is pretty old by now, but still - push.

**Comment by shyim** [comment]
I have currently no time. Feel free when somebody wants to create an PR 😊
