### ISSUE TITLE
Profiler page very slow under Shopware 5.6

### ISSUE THREAD

**Issue by tpertl** [FriendsOfShopware/FroshProfiler#112]
Hey,

for us it occurs, that loading the profiler with a maximum depth of the vardumper of 10000 and the maximal size of the vardumper of 10000 as well, is extremly decreasing the page load time of the profiler page.
Similar settings, even with higher depths and sizes, with Shopware 5.5 show no problems at all. 
We also tried it in a clean, freshly installed Shopware installation and the same problem occurs.
With a page load of close to 5 mins or more, it is basically not usable.

We'd be happy, if somebody could look into that. Cheers!

**Comment by shyim** [comment]
Can you disable html compression?

**Comment by tpertl** [comment]
Oh well, that was quite an easy solution! :D 
Thanks a lot mate!
