### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/FroshProfiler#113]
The composer dependencies should reflect the compatible Shopware version. Currently it's only in the `plugin.xml` which is useless if you require the profiler via composer.

Please add a proper version constraint on `shopware/shopware`

**Comment by shyim** [comment]
How should then the composer install and package for store work?

**Comment by hhoechtl** [comment]
I would define `shopware/shopware: "5.5.*"` as dev-dependency. This way if you do a `composer req frosh/shopware-profiler` it could determine the compatible version. If you pack the plugin for the store you should execute `install --no-dev -nao` and therefore Shopware will not be included.

**Comment by shyim** [comment]
But what's the benefit then when that is a dev-require?

**Comment by hhoechtl** [comment]
Ah, that only works if the plugin is itself a dev requirement. I though the requirements were taken from the install context, not the context of the inclusion. 

Then it must be a `require` and in the build process you can do `composer remove showpare/shopware` to undo the inclusion before packing.

**Comment by shyim** [comment]
Has been already solved by installing it using packages.friendsofshopware.com
