### ISSUE TITLE
Error after installation and activation

### ISSUE THREAD

**Issue by whynotOFC** [FriendsOfShopware/FroshProfiler#121]
Hi,

we use the plug-in in 5 different shops on different servers. However, after installing we get the same error message on all servers:

`PHP Fatal error: Cannot declare class Smarty_Resource, because the name is already in use in /home/web/www.XY.de/custom/plugins/FroshProfiler/Components/Smarty/sysplugins/smarty_resource.php on line 18`

We use Shopware 5.6.8 everywhere (ResponsiveTheme was tested and the error appears).

The plug-in version is 1.4.3 (but the error also occurred with 1.4.2).

Best regards and thanks for the great plug-in!

**Comment by shyim** [comment]
Which PHP version do you use?
