### ISSUE TITLE
I used the wrong email address in my commits

### ISSUE THREAD

**Issue by mjossdev** [FriendsOfShopware/FroshProfiler#127]
### Question

For my commits that were merged here I mistyped my email address, which unfortunately I did not realize until just now. I was able to fix it in my fork with a rebase and force push, but I don't know if doing a force push here would be OK. https://stackoverflow.com/questions/34850831/change-git-email-for-previous-commits

**Comment by dneustadt** [comment]
You can add multiple email addresses to your account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

That works retroactively so commits will be tied to your account once you add the email address you used to commit to your account.
