### ISSUE TITLE
Update auf Shopware 5.7.15 schlägt fehl wenn Plugin Plugin installiert

### ISSUE THREAD

**Issue by littlewonders-jg** [FriendsOfShopware/FroshProfiler#130]
### PHP Version

7.4.30

### Shopware Version

5.7.15

### Actual behaviour

Der Updatevorgang bricht mit folgender Fehlermeldung ab:
Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/custom/plugins/FroshProfiler/FroshProfiler.php:25 Stack trace: #0 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/custom/plugins/FroshProfiler/FroshProfiler.php(25): method_exists(NULL, 'getCacheDir') #1 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/composer/ClassLoader.php(571): include('/is/htdocs/wp13...') #2 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/is/htdocs/wp13...') #3 [internal function]: Composer\Autoload\ClassLoader->loadClass('FroshProfiler\\F...') #4 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/engine/Shopware/Bundle/PluginInstallerBundle/Service/PluginInitializer.php(119): class_exists('\\FroshProfiler\\...') #5 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/engine/Shopware/Kernel.php(495): Shopware\Bundle\PluginInstallerBundle\Service\PluginInitializer->initializePlugins() #6 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/engine/Shopware/Kernel.php(246): Shopware\Kernel->initializePlugins() #7 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/update/src/DependencyInjection/Container.php(178): Shopware\Kernel->boot() #8 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/pimple/pimple/src/Pimple/Container.php(122): Shopware\Recovery\Update\DependencyInjection\Container->Shopware\Recovery\Update\DependencyInjection\{closure}(Object(Pimple\Container)) #9 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/update/src/DependencyInjection/Container.php(187): Pimple\Container->offsetGet('shopware.contai...') #10 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/pimple/pimple/src/Pimple/Container.php(122): Shopware\Recovery\Update\DependencyInjection\Container->Shopware\Recovery\Update\DependencyInjection\{closure}(Object(Pimple\Container)) #11 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/src/DependencyInjection/Container.php(73): Pimple\Container->offsetGet('shopware.theme_...') #12 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/update/src/app.php(175): Shopware\Recovery\Common\DependencyInjection\Container->get('shopware.theme_...') #13 [internal function]: {closure}() #14 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #15 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch() #16 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #17 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #18 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call() #19 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/common/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call() #20 /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/recovery/update/index.php(57): Slim\Slim->run() #21 {main} thrown in /is/htdocs/wp13229909_2UPT9QUP9X/www/littlewonders_development/custom/plugins/FroshProfiler/FroshProfiler.php on line 25

### Expected behaviour

Shopware Update läuft zum Ende durch

### Steps to Reproduce?

1. Shopware < 5.7.15 aufsetzen
2. FroshProfiler installieren
3. Update auf 5.7.15 durchführen

**Comment by teiling88** [comment]
Hast Du die letzte Version des Plugins im Einsatz? Der Fehler sollte mit diesem Commit: https://github.com/FriendsOfShopware/FroshProfiler/commit/6ecf02ff8273f1c429a5ef25b831bf1bc048323d behoben sein.

**Comment by littlewonders-jg** [comment]
Ich habe Version 1.4.4 im Einsatz.

**Comment by teiling88** [comment]
Wenn Du die Anpassung aus den genannten Commits übernimmst, sollte der Fehler weg sein. Ich habe hier keine rechte o.ä. hier müsste mal ne neue Version released werden @shyim

**Comment by shyim** [comment]
1.4.5 ist jetzt im store
https://github.com/FriendsOfShopware/FroshProfiler/releases/tag/1.4.5
