### ISSUE TITLE
Deprecated Meldung auf PHP 8.1

### ISSUE THREAD

**Issue by littlewonders-jg** [FriendsOfShopware/FroshProfiler#131]
### PHP Version

8.1

### Shopware Version

5.7.15

### Actual behaviour

Wenn ich die PHP Version auf 8.1 umstelle erhalte ich folgende Meldung:
Deprecated: Implicit conversion from float 1663844067.342599 to int loses precision in /home/johannes/www/liebesschloss/custom/plugins/FroshProfiler/Components/Struct/Profile.php on line 193

Wenn ich in custom/plugins/FroshProfiler/Subscriber/DatabaseProfiler.php in Zeile 48 time() anstelle von microtime(true) einsetze erscheint die Deprecated Meldung nicht mehr. 

### Expected behaviour

Es soll auf PHP 8.1 so funktionieren wie auf PHP 7.4

### Steps to Reproduce?

Plugin auf PHP 8.1 einsetzen und in config.php error_reporting auf E_ALL & ~E_USER_DEPRECATED setzen

**Comment by shyim** [comment]
mach gerne einen PR
