### ISSUE TITLE
Article variant change via AJAX

### ISSUE THREAD

**Issue by Ch40s747** [FriendsOfShopware/FroshProfiler#70]
Article variant change via AJAX does not work if the Frosch Profiler is activated at the same time.

**Comment by shyim** [comment]
Could you provide informations like which Shopware version and so?

**Comment by Ch40s747** [comment]
I had version 1.2.0 of the Frosch Profiler in use. After update to version 1.2.1 it works together with Shopware 5.4.1. Sorry for the hoax!

**Comment by shyim** [comment]
@Ch40s747 Okay 😊
