### ISSUE TITLE
debug ajax requests

### ISSUE THREAD

**Issue by hlb-schmidt** [FriendsOfShopware/FroshProfiler#76]
i was hoping to findout which shopware events are fired when i select a filter in category listing. can we see this with this plugin? if yes, how?

if no, is there any other debugger/profiler - maybe on the server side - that shows us the fired shopware events for a http request?

**Comment by shyim** [comment]
You can open the main profile. You have in the left sidebar a Icon "Request". There are all XHR Requests are shown

**Comment by hlb-schmidt** [comment]
ok thanks!

ps. i should probably have first fixed the issue that all assets of this plugin are 404. i guess cause i have the cloned repo as symlink in custom/plugins, and smarty does not like that...
