### ISSUE TITLE
Add travis config for PHP 5.6

### ISSUE THREAD

**Issue by afoeder** [FriendsOfShopware/FroshProfiler#81]
In order to follow-up Shopware's compatibility with PHP 5.6 this plugin should be compatible as well and therefore offer such a configuration in Travis.

**Comment by fionera** [comment]
Since PHP 5.6 will loose Security Support in about 4 Months I dont think its neccesary

**Comment by shyim** [comment]
Hey, i am planning with the Release of Shopware 5.5 to make new versions only compatible to >= 7.1.
So i guess there is no need anymore :see_no_evil:

**Comment by shyim** [comment]
Unnecessary since https://github.com/FriendsOfShopware/FroshProfiler/commit/9b44552eb8f6f1c22e71d62ba5992afb8650a696
Now can be use typehints yayyyyyy :relaxed:
