### ISSUE TITLE
Error Message while using sw import tool

### ISSUE THREAD

**Issue by aweb3r** [FriendsOfShopware/FroshProfiler#86]
While FroshProfile is installed and enabled, it's not possible to import data like default_customer in my case. The Error-Message in backend wasnt helpful : "The EntityManager is closed."
I also tried to import viá bin/console, same behavior and error message.

Shopware 5.4.6
Build Rev 201807181357

Plugin Version: 1.3.0

**Comment by shyim** [comment]
Hey,
is there a way to get a anomiyzed file you try to import?

**Comment by shyim** [comment]
I cannot reproduce your issue.
