### ISSUE TITLE
Profiling Ajax Requests

### ISSUE THREAD

**Issue by buddhaCode** [FriendsOfShopware/FroshProfiler#88]
Moin,
is it somehow possible to profile AJAX requests like domain.tld/checkout/ajaxCart or loading the emotions? When i am looking at domain.tld/profiler none of the AJAX requests is logged. Another thing is strange. There are always only 10 profiles listed. Although, according to my settings there should be up to 50 profiles.

Here are my settings:
![bildschirmfoto 2018-09-19 um 09 38 02](https://user-images.githubusercontent.com/11678100/45738334-67092d80-bbf0-11e8-84be-49deca80bacb.png)

It thought whitelisting my client's ip (in this case localhost, coz i am on my local development machine) should profile this AJAX requests, as there is no toolbar displayed, obviously.

I am using Shopware 5.4.6 and plugin version 1.3.3

**Comment by buddhaCode** [comment]
Hm? In my installation the emotions are ajax requests and not sub-requests through the {action} view helper.
And what about the ajaxCart requests?

**Comment by shyim** [comment]
Ajax request will be shown as sub request. Currently real sub requests are not profiled. It's little bit stupid named

**Comment by buddhaCode** [comment]
Ahhhh, I see now. Thanks :) Maybe renaming it would be great ;) And is it possible to link the real subrequests with the main request?

**Comment by shyim** [comment]
Currently not implemented. feel free to create a pull request :)

**Comment by buddhaCode** [comment]
Will do when I find the time
