### ISSUE TITLE
What cache is profiled in the caching tab?

### ISSUE THREAD

**Issue by buddhaCode** [FriendsOfShopware/FroshProfiler#89]
Yeah, what cache is it? Opcache? APCu? File Cache? Doctrine Cache? Symfony HTTP Cache? Another Shopware cache? There are a lot of caches around ;)

**Comment by shyim** [comment]
Its the "core" Zend Cache from Shopware. So all configurations and services which use the DI service "cache".

**Comment by buddhaCode** [comment]
Great. I see.
