### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Component\Stopwatch\Stopwatch' not found

### ISSUE THREAD

**Issue by FloC3** [FriendsOfShopware/FroshProfiler#95]
Fatal error: Uncaught Error: Class 'Symfony\Component\Stopwatch\Stopwatch' not found in /xxx/xxx/shopware/var/cache/production_201812030839/proxies/ShopwareProductionc3df2d0d10d3bcd7b23aca7521dc539557a5511dProjectContainer.php:3176 Stack trace: #0 /xxx/xxx/shopware/vendor/symfony/dependency-injection/Container.php(306): ShopwareProductionc3df2d0d10d3bcd7b23aca7521dc539557a5511dProjectContainer->getFroshProfiler_StopWatchService() #1 /xxx/xxx/shopware/engine/Shopware/Components/DependencyInjection/Container.php(211): Symfony\Component\DependencyInjection\Container->get('frosh_profiler....', 1) #2 /xxx/xxx/shopware/engine/Shopware/Components/DependencyInjection/Container.php(143): Shopware\Components\DependencyInjection\Container->doLoad('frosh_profiler....', 1) #3 /kunden/426841_70794/rp-hosting in /xxx/xxx/shopware/var/cache/production_201812030839/proxies/ShopwareProductionc3df2d0d10d3bcd7b23aca7521dc539557a5511dProjectContainer.php on line 3176

**Comment by shyim** [comment]
Hey,
if you use the git version. Please run once composer install otherwise use packaged version in the release
