### ISSUE TITLE
5.5.4 says not licensed

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshProfiler#97]
Suddenly SW 5.5.4 says it is an unlicensed plugin which is weird.

**Comment by shyim** [comment]
I have already created an internal ticket for that. Tomorrow morning it should be "buyable" for free in the Community Store

**Comment by shyim** [comment]
Can be now bought for free in the store https://store.shopware.com/detail/index/sArticle/165750
